新增 README 內容: 網站原因和操作說明 #9
kevin38645/empty pull request #10
Opened 2023-11-16 04:50 UTC by fcu-d0843556

這個 PR 包含了我在 "update-readme" 分支上所做的變更，
主要是為了更新 README 檔案，新增了網站建立的原因和使用說明。

2023-11-16 04:52 UTC, kevin38645 requested changes
您好，我注意到 README 中缺少了安裝網頁的相關流程。
為了確保老師和其他專案成員能夠順利運行專案，
建議您將其內容添加到 README 文件中，謝謝。

2023-11-16 04:52 UTC, kevin38645 commented on README.md
>  網頁系統架構
請您在網頁系統架構的下面一行新增安裝流程。

2023-11-16 04:52 UTC, fcu-d0843556 commented on README.md
>  網頁系統架構
謝謝您的建議，我會檢查並進行對應的修改。

2023-11-16 04:55 UTC, fcu-d0843556 commented on README.md
>  網頁系統架構
我已經將安裝網頁的相關流程添加到 README 文件中。
請您再次查閱，如果還有其他需要改進的地方。
請隨時提出，謝謝。

2023-11-17 05:06 UTC, kevin38645 approved these changes
已再次審核，README 內容現在沒有問題。
批准本次合併請求。

2023-11-17 05:08 UTC, merged